###########################################################################
#
#	Makefile for hippisw
#
#	$Id: Makefile,v 1.4 1995/05/06 22:33:59 vwelch Exp $
#
###########################################################################

# Include file automatically generated by configure
include make.hippisw.inc

###########################################################################

LINK		=	$(CC) $(ARCH_LD_FLAGS)

###########################################################################

CFLAGS =	-g $(PROTOTYPES) $(REQUIRE_PASSWORD) $(SYSLOG_FACILITY) \
		-DMAGIC_STRING=\"$(MAGIC_STRING)\"  \
		-DCONFIG_FILE=\"$(CONFIG_FILE)\" $(ARCH_CC_FLAGS) \
		$(DEBUG)

# Sources for data structures
#
DSRCS	=	address_config.c address_map.c find.c hippiswd_conf.c \
		ip_addr.c logical_addr.c parse_file.c parse_token.c \
		path.c port_conf.c portlist.c read_config.c strqtok.c \
		switch.c switch_conf.c switch_map.c switchlist.c \
		version.c

INCS	=	address_config.h address_map.h basic_defines.h \
		client_request.h connections.h daemon_config.h find.h \
		handle_input.h handle_output.h ifield.h ip_addr.h logger.h \
		logical_addr.h parse_file.h parse_token.h password_config.h \
		path.h port.h portlist.h prompt.h read_config.h sw_output.h \
		switch.h switch_map.h switchlist.h telnet.h time_string.h

# Binary sources
BSRCS	=	harp.c hippi_cmd.c hippi_config.c ifield.c mksw.c 

DAEMON_SRCS =	hippiswd.c \
		connections.c client_request.c handle_input.c handle_output.c \
		logger.c password_config.c prompt.c telnet.c time_string.c

CLIENT_SRCS =	hippisw.c

MANPAGES =	config_hippi.5 config_hippi_passwd.5 hippi_utils.8 \
		hippisw.8 hippiswd.8

HIPPI_UTIL_LNS	=	harp.8 hippi_config.8 ifield.8 mksw.8

###########################################################################

SRCS	=	$(DSRCS) $(BSRCS) $(DAEMON_SRCS) $(CLIENT_SRCS) sw_output.c

BINS	=	hippi_config mksw ifield hippi_cmd harp hippiswd hippisw

###########################################################################

DOBJS	=	${DSRCS:.c=.o}

OBJS	=	${SRCS:.c=.o}

DAEMON_OBJS	=	${DAEMON_SRCS:.c=.o} $(DOBJS)

CLIENT_OBJS	=	${CLIENT_SRCS:.c=.o} $(DOBJS)

###########################################################################

default:	$(ARCH_DIR) $(ARCH_DIR)/Makefile $(ARCH_DIR)/make.hippisw.inc
		@(cd $(ARCH_DIR) ; make depend ; make internal )

$(ARCH_DIR):	$(SRCS) $(INCS)
	@if [ $(ARCH) = undefined ]; then \
		echo "------------------------" ; \
		echo "Run './configure' first." ; \
		echo "------------------------" ; \
		exit 1 ; \
	else	\
		echo "Building hippisw for $(ARCH)." ; \
	fi
	@if [ ! -d $(ARCH_DIR) ]; then \
		echo Making $(ARCH_DIR) directory ;\
		$(MKDIR) $(ARCH_DIR) ;\
	fi
	@(cd $(ARCH_DIR) ;\
		for file in $(SRCS) $(INCS) ; do \
			if [ ! -f $$file ]; then \
				ln -s ../$$file . ; \
			fi ;\
		done ;\
	)

$(ARCH_DIR)/Makefile:       Makefile
	@echo Copying Makefile to $(ARCH_DIR)/Makefile
	@cp Makefile $(ARCH_DIR)/Makefile

$(ARCH_DIR)/make.hippisw.inc:	make.hippisw.inc
	@echo Copying make.hippisw.inc to $(ARCH_DIR)/make.hippisw.inc
	@cp make.hippisw.inc $(ARCH_DIR)/make.hippisw.inc

internal:	$(BINS)

hippiswd:		$(DAEMON_OBJS)
	$(LINK) -o $@ $(DAEMON_OBJS)

hippisw:		$(CLIENT_OBJS)
	$(LINK) -o $@ $(CLIENT_OBJS)

ifield hippi_config harp:	$$@.o	$(DOBJS)
	$(LINK) -o $@ $@.o $(DOBJS)

mksw hippi_cmd:		$$@.o $(DOBJS) sw_output.o
	$(LINK) -o $@ $@.o $(DOBJS) sw_output.o

objects:	$(OBJS)

clean:
	@ if [ -d $(ARCH_DIR) ]; then \
		echo Cleaning up $(ARCH_DIR) directory ;\
		cd $(ARCH_DIR) ;\
		/bin/rm -f $(OBJS) *~ *.bak $(SRCS) $(INCS) Makefile depend ;\
	fi

clobber:
	@ if [ -d $(ARCH_DIR) ]; then \
		echo Removing $(ARCH_DIR) directory ;\
		/bin/rm -rf $(ARCH_DIR) ;\
	fi


depend:		$(SRCS) $(INCS) Makefile
	@echo
	@echo Updating Makefile dependancies
	@makedepend $(SRCS)
	@touch depend
	@echo Done.
	@echo

install:	default
	@if [ ! -d $(BIN_DIR) ]; then \
		echo Making $(BIN_DIR) ;\
		$(MKDIR) $(BIN_DIR) ;\
	fi
	@echo Installing binaries in $(BIN_DIR)
	@(cd $(ARCH_DIR); \
		$(STRIP) $(BINS) ;\
		$(INSTALL) $(BINS) $(BIN_DIR) )
	@if [ ! -d $(MAN_DIR) ]; then \
		echo Making $(MAN_DIR) ;\
		$(MKDIR) $(MAN_DIR) ;\
	fi
	@echo Installing man pages in $(MAN_DIR)
	@$(INSTALL) $(MANPAGES) $(MAN_DIR)
	@(cd $(MAN_DIR) ;\
		for file in $(HIPPI_UTIL_LNS) ; do \
			if [ ! -f $$file ]; then \
				ln -s hippi_utils.8 $$file ;\
			fi ;\
		done )

tags:
	etags *.c

###########################################################################


